# Generated by Django 3.0.5 on 2020-04-05 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=600)),
                ('views', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=datetime.date.today)),
                ('img_url', models.CharField(default='', max_length=100)),
                ('category', models.ManyToManyField(null=True, to='main.Category')),
                ('comments', models.ManyToManyField(null=True, to='main.Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
