# Generated by Django 3.0.5 on 2020-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200405_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
